version: "3.8"

services:
  devcontainer:
    image: ghcr.io/cpdevtools/dcm-images-devcontainers/typescript:next
    user: "node"
    volumes:
      - ..:/devcontainer:cached
      - bashhistory:/commandhistory
      - dcm-npm-cache:/home/vscode/.npm
      - dcm-pnpm-cache:/devcontainer/.pnpm-store
      - dcm-yarn-cache:/home/vscode/.cache/yarn
      - dcm-nuget-cache:/home/vscode/.nuget



volumes:
  bashhistory:
  dcm-nuget-cache:
    external: true
  dcm-pnpm-cache:
    external: true
  dcm-npm-cache:
    external: true
  dcm-yarn-cache:
    external: true
 